import type { NextRequest } from 'next/server'
import { NextResponse } from 'next/server'
import { supabaseAdmin } from '@/lib/supabase-admin'
import { financeBadRequest, financeUnauthorized, integerOr, numberOrNull, requireFinanceIdentity } from '@/lib/finance/api'
const modes=new Set(['spend','accumulate','repay']),kinds=new Set(['overdraft','debt','credit']),statuses=new Set(['active','paused','completed','cancelled']);type Context={params:Promise<{id:string}>};function legacyType(mode:string,kind:string|null){return mode==='repay'?(kind==='overdraft'?'overdraft':'debt'):mode==='accumulate'?'savings':'custom'}
const fields='id,name,goal_type,tracking_mode,repayment_kind,starting_balance,target_balance,target_amount,current_amount,target_date,priority,monthly_target,status,created_at,updated_at'
export async function GET(request:NextRequest,context:Context){const identity=await requireFinanceIdentity(request);if(!identity)return financeUnauthorized();const{id}=await context.params;const{data,error}=await supabaseAdmin.from('finance_goals').select(fields).eq('id',id).eq('user_id',identity.id).maybeSingle();if(error)return NextResponse.json({error:'finance_goal_unavailable',detail:error.message},{status:500});if(!data)return NextResponse.json({error:'Not found'},{status:404});return NextResponse.json({goal:data})}
export async function PATCH(request:NextRequest,context:Context){const identity=await requireFinanceIdentity(request);if(!identity)return financeUnauthorized();const{id}=await context.params;const body=await request.json().catch(()=>null) as Record<string,unknown>|null;if(!body)return financeBadRequest('Données invalides.');const patch:Record<string,unknown>={updated_at:new Date().toISOString()};let mode=body.tracking_mode?String(body.tracking_mode):null,kind=body.repayment_kind?String(body.repayment_kind):null;if(mode){if(!modes.has(mode))return financeBadRequest('Mode invalide.');patch.tracking_mode=mode;if(mode!=='repay'){patch.repayment_kind=null;patch.goal_type=legacyType(mode,null)}else if(kind&&kinds.has(kind)){patch.repayment_kind=kind;patch.goal_type=legacyType(mode,kind)}}if(kind&&!kinds.has(kind))return financeBadRequest('Type de remboursement invalide.');if('name'in body){const n=String(body.name??'').trim();if(!n)return financeBadRequest('Nom obligatoire.');patch.name=n}for(const key of ['target_amount','current_amount','monthly_target','starting_balance','target_balance'] as const){if(key in body)patch[key]=numberOrNull(body[key])}if('target_date'in body)patch.target_date=body.target_date?String(body.target_date):null;if('priority'in body)patch.priority=integerOr(body.priority,100);if('status'in body){const s=String(body.status);if(!statuses.has(s))return financeBadRequest('Statut invalide.');patch.status=s}const{data,error}=await supabaseAdmin.from('finance_goals').update(patch).eq('id',id).eq('user_id',identity.id).select(fields).maybeSingle();if(error)return NextResponse.json({error:'finance_goal_update_failed',detail:error.message},{status:500});if(!data)return NextResponse.json({error:'Not found'},{status:404});return NextResponse.json({goal:data})}
export async function DELETE(request:NextRequest,context:Context){const identity=await requireFinanceIdentity(request);if(!identity)return financeUnauthorized();const{id}=await context.params;const{data,error}=await supabaseAdmin.from('finance_goals').update({status:'cancelled',updated_at:new Date().toISOString()}).eq('id',id).eq('user_id',identity.id).select('id').maybeSingle();if(error)return NextResponse.json({error:'finance_goal_delete_failed',detail:error.message},{status:500});if(!data)return NextResponse.json({error:'Not found'},{status:404});return NextResponse.json({ok:true})}
