'use client'
import{useCallback,useEffect,useMemo,useState}from'react'
type Envelope={id:string;name:string;target_amount:number;spent_amount:number;cash_balance:number;cash_enabled:boolean;rollover_enabled:boolean;variance_amount:number;variance_status:'saved'|'overspent'|'on_target';default_action:'leave'|'rollover'}
type Saving={id:string;name:string;target_amount:number;current_amount:number;gap_amount:number;status:'missing'|'reached'|'exceeded'}
type SavingGoal={id:string;name:string;cycle_target:number;current_amount:number;gap_amount:number;status:'missing'|'reached'|'exceeded'}
type Destination={id:string;name:string}
type Preview={cycle:{start:string;end:string;label:string};envelopes:Envelope[];savings_destinations:Destination[];savings_summary:{envelopes:Saving[];goals:SavingGoal[];planned:number;actual:number};total_remainder:number;total_overspend:number;recent_closures:any[]}
type Action={envelope_id:string;action:'leave'|'rollover'|'save'|'return_to_bank';destination_envelope_id?:string}
const euro=(v:number)=>Number(v||0).toLocaleString('fr-FR',{maximumFractionDigits:2})+' €'
function savingStatus(status:string,gap:number){return status==='reached'?'Objectif atteint':status==='exceeded'?`Objectif dépassé de ${euro(Math.abs(gap))}`:`Il manque ${euro(Math.abs(gap))}`}
export default function FinanceCycleClosure(){
 const[p,setP]=useState<Preview|null>(null),[a,setA]=useState<Record<string,Action>>({}),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null)
 const load=useCallback(async()=>{setLoading(true);const r=await fetch('/api/finance/cycle/close-preview',{cache:'no-store'}),j=await r.json().catch(()=>({}));if(!r.ok)setError(j.detail||j.error||'Erreur');else{setP(j);const n:Record<string,Action>={};for(const e of j.envelopes??[])if(e.variance_amount>0)n[e.id]={envelope_id:e.id,action:e.rollover_enabled?'rollover':'leave'};setA(n)}setLoading(false)},[])
 useEffect(()=>{void load()},[load])
 const saveTotal=useMemo(()=>Object.values(a).reduce((s,x)=>x.action==='save'?s+Math.max(0,p?.envelopes.find(e=>e.id===x.envelope_id)?.variance_amount||0):s,0),[a,p])
 if(loading)return<section className="rounded-[28px] border p-6">Préparation…</section>
 const savingItems=[...(p?.savings_summary?.envelopes??[]).map(x=>({...x,target:x.target_amount})),...(p?.savings_summary?.goals??[]).map(x=>({...x,target:x.cycle_target}))]
 return <section className="rounded-[28px] border bg-[var(--novae-surface)] p-5 sm:p-7"><p className="text-xs font-black uppercase text-[var(--novae-primary)]">Clôture intelligente</p><h2 className="mt-2 text-3xl font-semibold">Fin de cycle</h2><p className="mt-2 text-sm text-[var(--novae-text-muted)]">Dépense : prévu − dépensé. Épargne : réellement épargné comparé au montant prévu.</p>{error&&<div className="mt-4 rounded-2xl bg-red-50 p-4 text-sm text-red-800">{error}</div>}
 <h3 className="mt-6 text-xl font-semibold">Dépenses</h3><div className="mt-3 grid gap-3">{p?.envelopes.map(e=>{const positive=e.variance_amount>0,negative=e.variance_amount<0,action=a[e.id];return<article key={e.id} className="rounded-2xl border p-4"><div className="flex flex-wrap justify-between gap-3"><div><strong>{e.name}</strong><p className="mt-1 text-xs text-[var(--novae-text-muted)]">Prévu {euro(e.target_amount)} · dépensé {euro(e.spent_amount)}</p></div><span className={`text-lg font-black ${negative?'text-red-700':positive?'text-emerald-700':''}`}>{positive?`Économisé ${euro(e.variance_amount)}`:negative?`Dépassement ${euro(-e.variance_amount)}`:'Budget respecté'}</span></div>{positive&&<div className="mt-4 grid gap-2 sm:grid-cols-2"><select value={action?.action??'leave'} onChange={ev=>setA(c=>({...c,[e.id]:{envelope_id:e.id,action:ev.target.value as Action['action'],destination_envelope_id:ev.target.value==='save'?(c[e.id]?.destination_envelope_id||p?.savings_destinations[0]?.id):undefined}}))} className="rounded-2xl border bg-[var(--novae-surface)] px-4 py-3 text-sm"><option value="leave">Laisser sur le compte</option><option value="rollover">Reporter au prochain cycle</option>{(p?.savings_destinations.length??0)>0&&<option value="save">Mettre en épargne</option>}{e.cash_enabled&&<option value="return_to_bank">Rendre les espèces au compte</option>}</select>{action?.action==='save'&&<select value={action.destination_envelope_id??''} onChange={ev=>setA(c=>({...c,[e.id]:{...action,destination_envelope_id:ev.target.value}}))} className="rounded-2xl border bg-[var(--novae-surface)] px-4 py-3 text-sm"><option value="">Choisir l’épargne</option>{p?.savings_destinations.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select>}</div>}</article>})}</div>
 <h3 className="mt-7 text-xl font-semibold">Épargne</h3>{savingItems.length===0?<div className="mt-3 rounded-2xl border border-dashed p-4 text-sm text-[var(--novae-text-muted)]">Aucune enveloppe ou objectif Épargne actif pour ce cycle.</div>:<div className="mt-3 grid gap-3">{savingItems.map(item=><article key={item.id} className="rounded-2xl border p-4"><div className="flex flex-wrap justify-between gap-3"><div><strong>{item.name}</strong><p className="mt-1 text-xs text-[var(--novae-text-muted)]">Prévu {euro(item.target)} · épargné {euro(item.current_amount)}</p></div><span className={`text-lg font-black ${item.status==='missing'?'text-amber-700':'text-emerald-700'}`}>{savingStatus(item.status,item.gap_amount)}</span></div></article>)}</div>}
 <div className="mt-5 grid gap-3 sm:grid-cols-4"><div className="rounded-2xl bg-black/5 p-4"><small>Économies potentielles</small><p className="mt-1 text-2xl font-black">{euro(p?.total_remainder??0)}</p></div><div className="rounded-2xl bg-black/5 p-4"><small>Dépassements</small><p className="mt-1 text-2xl font-black">{euro(p?.total_overspend??0)}</p></div><div className="rounded-2xl bg-black/5 p-4"><small>Épargne prévue</small><p className="mt-1 text-2xl font-black">{euro(p?.savings_summary?.planned??0)}</p></div><div className="rounded-2xl bg-black/5 p-4"><small>Épargne réalisée</small><p className="mt-1 text-2xl font-black">{euro(p?.savings_summary?.actual??0)}</p></div></div>{saveTotal>0&&<p className="mt-3 text-sm text-[var(--novae-text-muted)]">Réaffectation préparée vers l’épargne : <strong>{euro(saveTotal)}</strong></p>}</section>
}
