'use client'
import Link from 'next/link'
import { useCallback,useEffect,useState } from 'react'
type Mode='spend'|'accumulate'|'repay'
type YearStats={spent:number;injected:number;withdrawn:number;remainder_saved:number}
type Envelope={id:string;name:string;envelope_type:string;tracking_mode:Mode;target_amount:number|string;current_amount:number|string;cash_balance:number|string;rollover_enabled:boolean;cash_enabled:boolean;priority:number;year_stats?:YearStats}
const euro=(v:number|string)=>Number(v||0).toLocaleString('fr-FR',{maximumFractionDigits:2})+' €'
function copy(mode:Mode){if(mode==='repay')return{progress:'Remboursé',remaining:'Reste à rembourser',year:'Remboursé cette année'};if(mode==='accumulate')return{progress:'Épargné',remaining:'Reste à épargner',year:'Injecté cette année'};return{progress:'Dépensé ce cycle',remaining:'Reste à dépenser',year:'Dépensé cette année'}}
export default function FinanceEnvelopeDetail({id}:{id:string}){const[item,setItem]=useState<Envelope|null>(null),[error,setError]=useState<string|null>(null),[amount,setAmount]=useState(''),[note,setNote]=useState(''),[busy,setBusy]=useState(false)
 const load=useCallback(async()=>{try{const response=await fetch(`/api/finance/envelopes/${id}`,{cache:'no-store'});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.detail||payload.error||'Impossible de charger cette enveloppe.');setItem(payload.envelope);setError(null)}catch(reason){setError(reason instanceof Error?reason.message:'Erreur')}},[id]);useEffect(()=>{void load()},[load])
 async function move(action:'add'|'remove'|'cash_expense',bankEffect=false){setBusy(true);setError(null);const response=await fetch(`/api/finance/envelopes/${id}/movement`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,amount:Number(amount),bank_effect:bankEffect,note})});const payload=await response.json().catch(()=>({}));if(!response.ok)setError(payload.detail||payload.error||'Mouvement impossible.');else{setAmount('');setNote('');await load()}setBusy(false)}
 if(error&&!item)return<div className="rounded-[28px] border border-red-200 bg-red-50 p-6 text-red-800">{error}</div>;if(!item)return<div className="rounded-[28px] border border-[var(--novae-border)] bg-[var(--novae-surface)] p-6">Chargement…</div>
 const target=Number(item.target_amount||0),current=Number(item.current_amount||0),cash=Number(item.cash_balance||0),percent=target>0?Math.min(100,current/target*100):0,labels=copy(item.tracking_mode),year=item.year_stats??{spent:0,injected:0,withdrawn:0,remainder_saved:0}
 const delta=current-target,status=item.tracking_mode==='spend'?(delta<0?`${euro(-delta)} encore disponibles`:delta===0?'Budget utilisé exactement':`Dépassement de ${euro(delta)}`):(delta<0?`Il manque ${euro(-delta)}`:delta===0?'Objectif atteint':`Objectif dépassé de ${euro(delta)}`)
 return <div className="grid gap-5 lg:grid-cols-[1fr_.8fr]"><section className="rounded-[28px] border border-[var(--novae-border)] bg-[var(--novae-surface)] p-6 sm:p-8"><p className="text-xs font-black uppercase tracking-[.18em] text-[var(--novae-primary)]">Enveloppe · {item.tracking_mode==='spend'?'Dépense':item.tracking_mode==='accumulate'?'Épargne':'Remboursement'}</p><h2 className="mt-2 font-[var(--novae-font-title)] text-3xl font-semibold">{item.name}</h2><p className="mt-5 text-4xl font-black">{euro(current)} <span className="text-base font-semibold text-[var(--novae-text-muted)]">/ {euro(target)}</span></p><p className="mt-1 text-sm text-[var(--novae-text-muted)]">{labels.progress} · <strong>{status}</strong></p><div className="mt-4 h-3 overflow-hidden rounded-full bg-black/10"><div className="h-full rounded-full bg-[var(--novae-primary)]" style={{width:`${percent}%`}}/></div>
 <div className="mt-6 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-black/5 p-4"><p className="text-xs text-[var(--novae-text-muted)]">{labels.year}</p><p className="mt-1 font-black">{euro(item.tracking_mode==='spend'?year.spent:year.injected)}</p></div>{item.cash_enabled&&<div className="rounded-2xl bg-black/5 p-4"><p className="text-xs text-[var(--novae-text-muted)]">Espèces disponibles maintenant</p><p className="mt-1 font-black">{euro(cash)}</p></div>}{year.withdrawn>0&&<div className="rounded-2xl bg-black/5 p-4"><p className="text-xs text-[var(--novae-text-muted)]">Retiré cette année</p><p className="mt-1 font-black">{euro(year.withdrawn)}</p></div>}{year.remainder_saved>0&&<div className="rounded-2xl bg-black/5 p-4"><p className="text-xs text-[var(--novae-text-muted)]">Reliquats réaffectés à l’épargne</p><p className="mt-1 font-black">{euro(year.remainder_saved)}</p></div>}</div>
 <p className="mt-4 text-xs leading-5 text-[var(--novae-text-muted)]">Le montant suivi et les espèces sont deux choses différentes : une enveloppe Épargne peut contenir du cash, mais seules les injections/retraits modifient son épargne constituée.</p><Link href="/finances/envelopes" className="mt-5 inline-flex rounded-full border border-[var(--novae-border)] px-4 py-2 text-sm font-black text-[var(--novae-text-main)] no-underline">Modifier les paramètres</Link></section>
 <section className="rounded-[28px] border border-[var(--novae-border)] bg-[var(--novae-surface)] p-6"><p className="text-sm font-black">Ajuster maintenant</p><p className="mt-2 text-sm text-[var(--novae-text-muted)]">Utilise une injection/retrait pour corriger la progression. Le cash physique reste suivi séparément.</p><input value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Montant" inputMode="decimal" className="mt-4 w-full rounded-2xl border border-[var(--novae-border)] bg-transparent px-4 py-3"/><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Pourquoi ? (facultatif)" className="mt-3 w-full rounded-2xl border border-[var(--novae-border)] bg-transparent px-4 py-3"/><div className="mt-4 flex flex-wrap gap-2"><button disabled={busy||Number(amount)<=0} onClick={()=>void move('add',true)} className="rounded-full bg-[var(--novae-primary)] px-4 py-2 text-sm font-black text-white disabled:opacity-40">{item.cash_enabled&&item.tracking_mode==='spend'?'Ajouter des espèces depuis le compte':'Injecter depuis le compte'}</button><button disabled={busy||Number(amount)<=0} onClick={()=>void move('add',false)} className="rounded-full border border-[var(--novae-border)] px-4 py-2 text-sm font-black disabled:opacity-40">Corriger la progression</button><button disabled={busy||Number(amount)<=0} onClick={()=>void move('remove',false)} className="rounded-full border border-[var(--novae-border)] px-4 py-2 text-sm font-black disabled:opacity-40">Corriger à la baisse</button>{item.cash_enabled&&<button disabled={busy||Number(amount)<=0} onClick={()=>void move('cash_expense',false)} className="rounded-full border border-[var(--novae-border)] px-4 py-2 text-sm font-black disabled:opacity-40">J’ai payé en cash</button>}</div>{error&&<p className="mt-3 text-sm text-red-700">{error}</p>}</section></div>}
