'use client'

import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'

type Profile = {
  usual_income_day:number|null
  usual_net_income:number|null
  current_overdraft:number
  overdraft_limit:number
  analysis_period_months:number
  safety_floor:number
  onboarding_completed_at?:string|null
}
type EnvelopeRec={key:string;name:string;envelope_type:string;target_amount:number;rollover_enabled:boolean;cash_enabled:boolean;reason:string;confidence:string}
type GoalRec={key:string;name:string;goal_type:string;target_amount:number;monthly_target:number|null;reason:string;confidence:string}
type Recommendations={context:{months_analysed:number;transactions_count:number;observed_monthly_income:number|null;observed_monthly_expenses:number|null;recurring_commitments:number;basis:string[]};envelopes:EnvelopeRec[];goals:GoalRec[];warnings:string[]}
type Intelligence={summary:{total:number;categorised:number;uncategorised:number;subscriptions:number;installments:number;recurring:number};expense_total:number;categories:Array<{id:string;name:string;amount:number;percentage:number}>}

const euro=(value:number|null|undefined)=>value==null?'—':Number(value).toLocaleString('fr-FR',{maximumFractionDigits:0})+' €'
const toNumber=(value:string)=>{const n=Number(value.replace(',','.'));return Number.isFinite(n)?n:0}

export default function FinanceOnboardingWizard(){
  const [step,setStep]=useState(1)
  const [loading,setLoading]=useState(true)
  const [saving,setSaving]=useState(false)
  const [error,setError]=useState<string|null>(null)
  const [done,setDone]=useState(false)
  const [profile,setProfile]=useState<Profile>({usual_income_day:null,usual_net_income:null,current_overdraft:0,overdraft_limit:0,analysis_period_months:3,safety_floor:0})
  const [hasOverdraft,setHasOverdraft]=useState(false)
  const [recs,setRecs]=useState<Recommendations|null>(null)
  const [intel,setIntel]=useState<Intelligence|null>(null)
  const [selectedEnvelopes,setSelectedEnvelopes]=useState<Record<string,boolean>>({})
  const [selectedGoals,setSelectedGoals]=useState<Record<string,boolean>>({})
  const [envelopeAmounts,setEnvelopeAmounts]=useState<Record<string,string>>({})
  const [goalAmounts,setGoalAmounts]=useState<Record<string,string>>({})
  const [goalMonthly,setGoalMonthly]=useState<Record<string,string>>({})

  useEffect(()=>{let active=true;(async()=>{try{
    const [p,r,i]=await Promise.all([fetch('/api/finance/profile',{cache:'no-store'}),fetch('/api/finance/recommendations',{cache:'no-store'}),fetch('/api/finance/transactions/intelligence',{cache:'no-store'})])
    const pp=await p.json().catch(()=>({})),rr=await r.json().catch(()=>({})),ii=await i.json().catch(()=>({}))
    if(!p.ok)throw new Error(pp.detail||pp.error||'Profil Finance indisponible.')
    if(!active)return
    const current=pp.profile||{}
    const next:Profile={usual_income_day:current.usual_income_day??null,usual_net_income:current.usual_net_income==null?null:Number(current.usual_net_income),current_overdraft:Number(current.current_overdraft||0),overdraft_limit:Number(current.overdraft_limit||0),analysis_period_months:Number(current.analysis_period_months||3),safety_floor:Number(current.safety_floor||0),onboarding_completed_at:current.onboarding_completed_at||null}
    setProfile(next);setHasOverdraft(next.current_overdraft>0)
    if(r.ok){setRecs(rr);const se:Record<string,boolean>={},sg:Record<string,boolean>={},ea:Record<string,string>={},ga:Record<string,string>={},gm:Record<string,string>={};(rr.envelopes||[]).forEach((x:EnvelopeRec)=>{se[x.key]=true;ea[x.key]=String(x.target_amount)});(rr.goals||[]).forEach((x:GoalRec)=>{sg[x.key]=true;ga[x.key]=String(x.target_amount);gm[x.key]=x.monthly_target==null?'':String(x.monthly_target)});setSelectedEnvelopes(se);setSelectedGoals(sg);setEnvelopeAmounts(ea);setGoalAmounts(ga);setGoalMonthly(gm)}
    if(i.ok)setIntel(ii)
  }catch(e){if(active)setError(e instanceof Error?e.message:'Erreur.')}finally{if(active)setLoading(false)}})();return()=>{active=false}},[])

  const selectedCount=useMemo(()=>Object.values(selectedEnvelopes).filter(Boolean).length+Object.values(selectedGoals).filter(Boolean).length,[selectedEnvelopes,selectedGoals])
  const saveProfile=async(completed=false)=>{const response=await fetch('/api/finance/profile',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({usual_net_income:profile.usual_net_income,usual_income_day:profile.usual_income_day,current_overdraft:hasOverdraft?profile.current_overdraft:0,overdraft_limit:hasOverdraft?profile.overdraft_limit:0,safety_floor:profile.safety_floor,analysis_period_months:profile.analysis_period_months,onboarding_completed:completed})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.detail||payload.error||'Impossible d’enregistrer le profil.')}
  const finish=async()=>{setSaving(true);setError(null);try{await saveProfile(false);const envelopes=(recs?.envelopes||[]).filter(x=>selectedEnvelopes[x.key]).map(x=>({...x,target_amount:toNumber(envelopeAmounts[x.key]??String(x.target_amount))}));const goals=(recs?.goals||[]).filter(x=>selectedGoals[x.key]).map(x=>({...x,target_amount:toNumber(goalAmounts[x.key]??String(x.target_amount)),monthly_target:goalMonthly[x.key]?toNumber(goalMonthly[x.key]):null}));if(envelopes.length||goals.length){const response=await fetch('/api/finance/recommendations/apply',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({confirmed:true,envelopes,goals})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.detail||payload.error||'Impossible d’appliquer les propositions.')};await saveProfile(true);setDone(true)}catch(e){setError(e instanceof Error?e.message:'Erreur.')}finally{setSaving(false)}}

  if(loading)return <div className="rounded-[28px] border border-[var(--novae-border)] bg-[var(--novae-surface)] p-6">Préparation de ton diagnostic Finance…</div>
  if(done)return <div className="rounded-[28px] border border-[var(--novae-border)] bg-[var(--novae-surface)] p-6 sm:p-8"><p className="text-xs font-black uppercase tracking-[.18em] text-[var(--novae-primary)]">Configuration terminée</p><h2 className="mt-2 font-[var(--novae-font-title)] text-3xl font-semibold">Ton pilotage est prêt.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[var(--novae-text-muted)]">Les montants restent modifiables à tout moment. Nova continuera d’apprendre de tes transactions et proposera des recalibrages sans rien changer sans ton accord.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/finances" className="rounded-full bg-[var(--novae-primary)] px-5 py-3 text-sm font-black text-white no-underline">Voir mon tableau de bord</Link><Link href="/finances/analysis" className="rounded-full border border-[var(--novae-border)] px-5 py-3 text-sm font-black no-underline">Voir l’analyse</Link></div></div>

  return <div className="grid gap-5">
    <section className="rounded-[28px] border border-[var(--novae-border)] bg-[var(--novae-surface)] p-5 sm:p-7"><p className="text-xs font-black uppercase tracking-[.18em] text-[var(--novae-primary)]">Onboarding Finance · {step}/4</p><h2 className="mt-2 font-[var(--novae-font-title)] text-3xl font-semibold">{step===1?'Posons ton cadre réel':step===2?'Ta situation de compte':step===3?'Ce que Nova observe':'Propositions à valider'}</h2><div className="mt-4 h-2 overflow-hidden rounded-full bg-black/10"><div className="h-full rounded-full bg-[var(--novae-primary)] transition-all" style={{width:`${step*25}%`}}/></div></section>

    {step===1&&<section className="rounded-[28px] border border-[var(--novae-border)] bg-[var(--novae-surface)] p-5 sm:p-7"><p className="text-sm text-[var(--novae-text-muted)]">Ces informations servent au calcul. Elles ne créent aucune transaction.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-black">Revenu net habituel<input className="mt-2 w-full rounded-2xl border border-[var(--novae-border)] bg-transparent px-4 py-3" inputMode="decimal" value={profile.usual_net_income??''} onChange={e=>setProfile(p=>({...p,usual_net_income:e.target.value===''?null:toNumber(e.target.value)}))}/></label><label className="text-sm font-black">Jour habituel de rentrée d’argent<input className="mt-2 w-full rounded-2xl border border-[var(--novae-border)] bg-transparent px-4 py-3" inputMode="numeric" min={1} max={31} value={profile.usual_income_day??''} onChange={e=>setProfile(p=>({...p,usual_income_day:e.target.value===''?null:Math.min(31,Math.max(1,Number(e.target.value)||1))}))}/></label><label className="text-sm font-black">Plancher de sécurité sur le compte<input className="mt-2 w-full rounded-2xl border border-[var(--novae-border)] bg-transparent px-4 py-3" inputMode="decimal" value={profile.safety_floor} onChange={e=>setProfile(p=>({...p,safety_floor:Math.max(0,toNumber(e.target.value))}))}/><span className="mt-2 block text-xs font-medium text-[var(--novae-text-muted)]">Une fois hors découvert, Nova ne considérera pas cette somme comme libre.</span></label><label className="text-sm font-black">Historique à analyser<select className="mt-2 w-full rounded-2xl border border-[var(--novae-border)] bg-transparent px-4 py-3" value={profile.analysis_period_months} onChange={e=>setProfile(p=>({...p,analysis_period_months:Number(e.target.value)}))}><option value={3}>3 mois</option><option value={6}>6 mois</option></select></label></div></section>}

    {step===2&&<section className="rounded-[28px] border border-[var(--novae-border)] bg-[var(--novae-surface)] p-5 sm:p-7"><label className="flex items-start gap-3 rounded-2xl border border-[var(--novae-border)] p-4"><input type="checkbox" className="mt-1" checked={hasOverdraft} onChange={e=>setHasOverdraft(e.target.checked)}/><span><strong>J’ai actuellement un découvert à résorber</strong><span className="mt-1 block text-sm text-[var(--novae-text-muted)]">Laisse décoché si ce n’est pas ton cas. Finance ne suppose jamais que tu es à découvert.</span></span></label>{hasOverdraft&&<div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-black">Découvert actuel à récupérer<input className="mt-2 w-full rounded-2xl border border-[var(--novae-border)] bg-transparent px-4 py-3" inputMode="decimal" value={profile.current_overdraft} onChange={e=>setProfile(p=>({...p,current_overdraft:Math.max(0,toNumber(e.target.value))}))}/></label><label className="text-sm font-black">Découvert autorisé<input className="mt-2 w-full rounded-2xl border border-[var(--novae-border)] bg-transparent px-4 py-3" inputMode="decimal" value={profile.overdraft_limit} onChange={e=>setProfile(p=>({...p,overdraft_limit:Math.max(0,toNumber(e.target.value))}))}/></label></div>}<div className="mt-5 rounded-2xl bg-black/5 p-4 text-sm"><strong>Règle automatique :</strong> tant que le solde est négatif, Nova suit la progression vers 0. Une fois 0 atteint, le plancher de sécurité reprend le relais.</div></section>}

    {step===3&&<section className="grid gap-4"><div className="grid gap-3 sm:grid-cols-4"><Metric label="Opérations analysées" value={String(intel?.summary.total??recs?.context.transactions_count??0)}/><Metric label="Catégorisées" value={String(intel?.summary.categorised??0)}/><Metric label="Récurrences" value={String(intel?.summary.recurring??0)}/><Metric label="Dépenses observées" value={euro(recs?.context.observed_monthly_expenses)+'/mois'}/></div><div className="rounded-[28px] border border-[var(--novae-border)] bg-[var(--novae-surface)] p-5 sm:p-7"><h3 className="text-xl font-black">Principales catégories observées</h3>{(intel?.categories||[]).length===0?<p className="mt-3 text-sm text-[var(--novae-text-muted)]">Pas encore assez de transactions catégorisées. Tu peux continuer quand même et ajuster plus tard.</p>:<div className="mt-4 grid gap-2">{intel!.categories.slice(0,6).map(c=><div key={c.id} className="flex items-center justify-between gap-4 rounded-2xl bg-black/5 px-4 py-3"><span className="font-bold">{c.name}</span><span className="text-sm font-black">{euro(c.amount)} · {c.percentage}%</span></div>)}</div>}{recs?.warnings?.length?<div className="mt-4 rounded-2xl bg-amber-50 p-4 text-sm text-amber-950">{recs.warnings.join(' ')}</div>:null}</div></section>}

    {step===4&&<section className="grid gap-4"><div className="rounded-[28px] border border-[var(--novae-border)] bg-[var(--novae-surface)] p-5 sm:p-7"><h3 className="text-xl font-black">Enveloppes proposées</h3>{(recs?.envelopes||[]).length===0?<p className="mt-3 text-sm text-[var(--novae-text-muted)]">Aucune nouvelle enveloppe nécessaire : tes enveloppes existantes sont conservées.</p>:<div className="mt-4 grid gap-3">{recs!.envelopes.map(x=><label key={x.key} className="grid gap-3 rounded-2xl border border-[var(--novae-border)] p-4 sm:grid-cols-[auto_1fr_140px]"><input type="checkbox" className="mt-1" checked={!!selectedEnvelopes[x.key]} onChange={e=>setSelectedEnvelopes(s=>({...s,[x.key]:e.target.checked}))}/><span><strong>{x.name}</strong><span className="mt-1 block text-xs text-[var(--novae-text-muted)]">{x.reason}</span></span><input aria-label={`Montant ${x.name}`} className="rounded-xl border border-[var(--novae-border)] bg-transparent px-3 py-2 font-black" inputMode="decimal" value={envelopeAmounts[x.key]??''} onChange={e=>setEnvelopeAmounts(s=>({...s,[x.key]:e.target.value}))}/></label>)}</div>}</div><div className="rounded-[28px] border border-[var(--novae-border)] bg-[var(--novae-surface)] p-5 sm:p-7"><h3 className="text-xl font-black">Objectifs proposés</h3>{(recs?.goals||[]).length===0?<p className="mt-3 text-sm text-[var(--novae-text-muted)]">Aucun nouvel objectif imposé. Tu peux créer librement les tiens plus tard.</p>:<div className="mt-4 grid gap-3">{recs!.goals.map(x=><label key={x.key} className="grid gap-3 rounded-2xl border border-[var(--novae-border)] p-4 sm:grid-cols-[auto_1fr_120px_120px]"><input type="checkbox" className="mt-1" checked={!!selectedGoals[x.key]} onChange={e=>setSelectedGoals(s=>({...s,[x.key]:e.target.checked}))}/><span><strong>{x.name}</strong><span className="mt-1 block text-xs text-[var(--novae-text-muted)]">{x.reason}</span></span><input aria-label={`Cible ${x.name}`} className="rounded-xl border border-[var(--novae-border)] bg-transparent px-3 py-2 font-black" value={goalAmounts[x.key]??''} onChange={e=>setGoalAmounts(s=>({...s,[x.key]:e.target.value}))}/><input aria-label={`Mensuel ${x.name}`} placeholder="€/mois" className="rounded-xl border border-[var(--novae-border)] bg-transparent px-3 py-2 font-black" value={goalMonthly[x.key]??''} onChange={e=>setGoalMonthly(s=>({...s,[x.key]:e.target.value}))}/></label>)}</div>}</div><div className="rounded-2xl bg-black/5 p-4 text-sm"><strong>{selectedCount} proposition(s) sélectionnée(s).</strong> Rien ne sera créé sans le bouton de validation ci-dessous.</div></section>}

    {error&&<div className="rounded-2xl bg-red-50 p-4 text-sm text-red-800">{error}</div>}
    <div className="flex flex-wrap justify-between gap-3">{step>1?<button onClick={()=>setStep(s=>s-1)} className="rounded-full border border-[var(--novae-border)] px-5 py-3 text-sm font-black">← Précédent</button>:<Link href="/finances" className="rounded-full border border-[var(--novae-border)] px-5 py-3 text-sm font-black no-underline">Plus tard</Link>}{step<4?<button onClick={async()=>{if(step===1||step===2){try{setSaving(true);await saveProfile(false)}catch(e){setError(e instanceof Error?e.message:'Erreur.');return}finally{setSaving(false)}}setStep(s=>s+1)}} disabled={saving} className="rounded-full bg-[var(--novae-primary)] px-5 py-3 text-sm font-black text-white disabled:opacity-50">Continuer →</button>:<button onClick={()=>void finish()} disabled={saving} className="rounded-full bg-[var(--novae-primary)] px-5 py-3 text-sm font-black text-white disabled:opacity-50">{saving?'Validation…':'Valider mon pilotage'}</button>}</div>
  </div>
}

function Metric({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-[var(--novae-border)] bg-[var(--novae-surface)] p-4"><p className="text-xs font-bold text-[var(--novae-text-muted)]">{label}</p><p className="mt-1 text-xl font-black">{value}</p></div>}
