'use client'
import Link from 'next/link'
import { useEffect, useState } from 'react'

type Goal = { id:string; name:string; goal_type:string; target_amount:number|string; current_amount:number|string; target_date:string|null; priority:number; monthly_target:number|string|null; status:string }
export default function FinanceGoalDetail({ id }: { id:string }) {
 const [item,setItem]=useState<Goal|null>(null); const [error,setError]=useState<string|null>(null)
 useEffect(()=>{fetch(`/api/finance/goals/${id}`,{cache:'no-store'}).then(async r=>{const p=await r.json().catch(()=>({})); if(!r.ok) throw new Error(p.detail||p.error||'Impossible de charger cet objectif.'); setItem(p.goal)}).catch(e=>setError(e instanceof Error?e.message:'Erreur'))},[id])
 if(error) return <div className="rounded-[28px] border border-red-200 bg-red-50 p-6 text-red-800">{error}</div>
 if(!item) return <div className="rounded-[28px] border border-[var(--novae-border)] bg-[var(--novae-surface)] p-6">Chargement…</div>
 const target=Number(item.target_amount||0), current=Number(item.current_amount||0), percent=target>0?Math.min(100,current/target*100):0
 return <section className="rounded-[28px] border border-[var(--novae-border)] bg-[var(--novae-surface)] p-6 sm:p-8"><p className="text-xs font-black uppercase tracking-[.18em] text-[var(--novae-primary)]">Objectif</p><h2 className="mt-2 font-[var(--novae-font-title)] text-3xl font-semibold">{item.name}</h2><p className="mt-5 text-4xl font-black">{current.toLocaleString('fr-FR')} € <span className="text-base font-semibold text-[var(--novae-text-muted)]">/ {target.toLocaleString('fr-FR')} €</span></p><div className="mt-4 h-3 overflow-hidden rounded-full bg-black/10"><div className="h-full rounded-full bg-[var(--novae-primary)]" style={{width:`${percent}%`}}/></div><p className="mt-2 text-sm text-[var(--novae-text-muted)]">{Math.round(percent)} % atteint</p><div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-black/5 p-4"><p className="text-xs text-[var(--novae-text-muted)]">Priorité</p><p className="mt-1 font-black">{item.priority}</p></div><div className="rounded-2xl bg-black/5 p-4"><p className="text-xs text-[var(--novae-text-muted)]">Par mois</p><p className="mt-1 font-black">{item.monthly_target?`${Number(item.monthly_target).toLocaleString('fr-FR')} €`:'Non défini'}</p></div><div className="rounded-2xl bg-black/5 p-4"><p className="text-xs text-[var(--novae-text-muted)]">Échéance</p><p className="mt-1 font-black">{item.target_date?new Date(item.target_date+'T00:00:00').toLocaleDateString('fr-FR'):'Libre'}</p></div></div><Link href="/finances/goals" className="mt-6 inline-flex rounded-full border border-[var(--novae-border)] px-4 py-2 text-sm font-black text-[var(--novae-text-main)] no-underline">Modifier depuis mes objectifs</Link></section>
}
