'use client'
import { useCallback,useEffect,useState } from 'react'
type Commitment={id:string;name:string;commitment_type:string;amount:number|string;frequency:string;next_due_date:string|null}
type Provision={id:string;name:string;target_amount:number|string;current_reserved:number|string;due_date:string|null;monthly_amount:number|string}
const e=(v:number|string)=>Number(v||0).toLocaleString('fr-FR',{maximumFractionDigits:2})+' €'
export default function FinanceUpcomingManager(){const [c,setC]=useState<Commitment[]>([]),[p,setP]=useState<Provision[]>([]),[name,setName]=useState(''),[amount,setAmount]=useState(''),[date,setDate]=useState(''),[pname,setPname]=useState(''),[ptarget,setPtarget]=useState(''),[pdate,setPdate]=useState(''),[error,setError]=useState<string|null>(null)
 const load=useCallback(async()=>{const[a,b]=await Promise.all([fetch('/api/finance/upcoming',{cache:'no-store'}),fetch('/api/finance/provisions',{cache:'no-store'})]);const ap=await a.json().catch(()=>({})),bp=await b.json().catch(()=>({}));if(a.ok)setC(ap.commitments||[]);if(b.ok)setP(bp.provisions||[])},[]);useEffect(()=>{void load()},[load])
 async function addCommit(){setError(null);const r=await fetch('/api/finance/upcoming',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name,amount:Number(amount),commitment_type:'bill',frequency:'monthly',next_due_date:date||null})});const x=await r.json().catch(()=>({}));if(!r.ok)setError(x.detail||x.error);else{setName('');setAmount('');setDate('');await load()}}
 async function addProvision(){setError(null);const r=await fetch('/api/finance/provisions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:pname,target_amount:Number(ptarget),due_date:pdate||null})});const x=await r.json().catch(()=>({}));if(!r.ok)setError(x.detail||x.error);else{setPname('');setPtarget('');setPdate('');await load()}}
 async function del(kind:'c'|'p',id:string){await fetch(kind==='c'?`/api/finance/upcoming?id=${id}`:`/api/finance/provisions?id=${id}`,{method:'DELETE'});await load()}
 return <div className="grid gap-5 lg:grid-cols-2"><section className="rounded-[28px] border border-[var(--novae-border)] bg-[var(--novae-surface)] p-5 sm:p-7"><p className="text-xs font-black uppercase tracking-[.18em] text-[var(--novae-primary)]">Charges fixes</p><h2 className="mt-2 text-2xl font-black">À réserver avant de dépenser</h2><div className="mt-4 grid gap-2">{c.map(x=><div key={x.id} className="flex items-center justify-between gap-3 rounded-2xl bg-black/5 p-4"><span><strong>{x.name}</strong><small className="block text-[var(--novae-text-muted)]">{x.next_due_date||'date non précisée'}</small></span><span className="text-right"><strong>{e(x.amount)}</strong><button onClick={()=>void del('c',x.id)} className="ml-3 text-xs text-red-700">Retirer</button></span></div>)}</div><div className="mt-4 grid gap-2 sm:grid-cols-3"><input value={name} onChange={x=>setName(x.target.value)} placeholder="Électricité" className="rounded-2xl border border-[var(--novae-border)] bg-transparent px-3 py-3"/><input value={amount} onChange={x=>setAmount(x.target.value)} placeholder="70" inputMode="decimal" className="rounded-2xl border border-[var(--novae-border)] bg-transparent px-3 py-3"/><input value={date} onChange={x=>setDate(x.target.value)} type="date" className="rounded-2xl border border-[var(--novae-border)] bg-transparent px-3 py-3"/></div><button onClick={()=>void addCommit()} disabled={!name||Number(amount)<=0} className="mt-3 rounded-full bg-[var(--novae-primary)] px-4 py-2 text-sm font-black text-white disabled:opacity-40">Ajouter la charge</button></section>
 <section className="rounded-[28px] border border-[var(--novae-border)] bg-[var(--novae-surface)] p-5 sm:p-7"><p className="text-xs font-black uppercase tracking-[.18em] text-[var(--novae-primary)]">Provisions</p><h2 className="mt-2 text-2xl font-black">Les grosses dépenses deviennent petites</h2><p className="mt-2 text-sm text-[var(--novae-text-muted)]">Rentrée, Noël, assurance annuelle, voyage scolaire… Nova calcule combien réserver chaque mois.</p><div className="mt-4 grid gap-2">{p.map(x=><div key={x.id} className="rounded-2xl bg-black/5 p-4"><div className="flex justify-between gap-3"><strong>{x.name}</strong><button onClick={()=>void del('p',x.id)} className="text-xs text-red-700">Retirer</button></div><p className="mt-2 text-sm">Objectif {e(x.target_amount)} · provision conseillée <strong>{e(x.monthly_amount)}/mois</strong></p></div>)}</div><div className="mt-4 grid gap-2 sm:grid-cols-3"><input value={pname} onChange={x=>setPname(x.target.value)} placeholder="Rentrée scolaire" className="rounded-2xl border border-[var(--novae-border)] bg-transparent px-3 py-3"/><input value={ptarget} onChange={x=>setPtarget(x.target.value)} placeholder="500" inputMode="decimal" className="rounded-2xl border border-[var(--novae-border)] bg-transparent px-3 py-3"/><input value={pdate} onChange={x=>setPdate(x.target.value)} type="date" className="rounded-2xl border border-[var(--novae-border)] bg-transparent px-3 py-3"/></div><button onClick={()=>void addProvision()} disabled={!pname||Number(ptarget)<=0} className="mt-3 rounded-full border border-[var(--novae-primary)] px-4 py-2 text-sm font-black text-[var(--novae-primary)] disabled:opacity-40">Créer la provision</button></section>{error&&<div className="rounded-2xl bg-red-50 p-4 text-red-800 lg:col-span-2">{error}</div>}</div>}
