'use client'
import { useCallback, useEffect, useState } from 'react'
type Forecast={base_balance:number|null;pending_bank_delta:number;commitments_total:number;provisions_total:number;safety_floor:number;projected_bank_balance:number|null;real_available:number|null;next_income_date:string|null;cash_total:number}
type Recal={envelope_id:string;name:string;current_target:number;suggested_target:number;adjustments_count:number;average_extra:number;reason:string}
type Close={surplus:number;cash_remainder:number;message:string;suggested_goal:{name:string}|null}
const euro=(v:number|null|undefined)=>v==null?'—':v.toLocaleString('fr-FR',{maximumFractionDigits:2})+' €'
export default function FinanceAnalysisPlanner(){const [f,setF]=useState<Forecast|null>(null),[spend,setSpend]=useState('0'),[save,setSave]=useState('0'),[recal,setRecal]=useState<Recal[]>([]),[close,setClose]=useState<Close|null>(null),[error,setError]=useState<string|null>(null)
 const load=useCallback(async(s='0',sv='0')=>{const [a,b,c]=await Promise.all([fetch(`/api/finance/forecast?extra_spend=${encodeURIComponent(s)}&extra_savings=${encodeURIComponent(sv)}`,{cache:'no-store'}),fetch('/api/finance/recalibration',{cache:'no-store'}),fetch('/api/finance/cycle/close-preview',{cache:'no-store'})]);const ap=await a.json().catch(()=>({})),bp=await b.json().catch(()=>({})),cp=await c.json().catch(()=>({}));if(a.ok)setF(ap);else setError(ap.detail||ap.error);if(b.ok)setRecal(bp.suggestions||[]);if(c.ok)setClose(cp)},[]);useEffect(()=>{void load()},[load])
 return <div className="grid gap-5"><section className="rounded-[28px] border border-[var(--novae-border)] bg-[var(--novae-surface)] p-5 sm:p-7"><p className="text-xs font-black uppercase tracking-[.18em] text-[var(--novae-primary)]">Et si ?</p><h2 className="mt-2 font-[var(--novae-font-title)] text-3xl font-semibold">Simuler avant de décider</h2><div className="mt-5 grid gap-3 sm:grid-cols-2"><label className="text-sm font-black">Dépense supplémentaire<input value={spend} onChange={e=>setSpend(e.target.value)} inputMode="decimal" className="mt-2 w-full rounded-2xl border border-[var(--novae-border)] bg-transparent px-4 py-3"/></label><label className="text-sm font-black">Épargne supplémentaire<input value={save} onChange={e=>setSave(e.target.value)} inputMode="decimal" className="mt-2 w-full rounded-2xl border border-[var(--novae-border)] bg-transparent px-4 py-3"/></label></div><button onClick={()=>void load(spend,save)} className="mt-4 rounded-full bg-[var(--novae-primary)] px-5 py-3 text-sm font-black text-white">Recalculer</button><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-black/5 p-4"><small>Solde prévu</small><p className="mt-1 text-2xl font-black">{euro(f?.projected_bank_balance)}</p></div><div className="rounded-2xl bg-black/5 p-4"><small>Disponible réel</small><p className="mt-1 text-2xl font-black">{euro(f?.real_available)}</p></div><div className="rounded-2xl bg-black/5 p-4"><small>Prochaine paie</small><p className="mt-1 text-xl font-black">{f?.next_income_date||'—'}</p></div></div></section>
 <section className="rounded-[28px] border border-[var(--novae-border)] bg-[var(--novae-surface)] p-5 sm:p-7"><p className="text-sm font-black">Nova apprend des ajustements récurrents</p>{recal.length===0?<p className="mt-2 text-sm text-[var(--novae-text-muted)]">Pas encore assez d’ajustements répétés. Nova attend plusieurs cycles avant de proposer un nouveau budget de référence.</p>:<div className="mt-4 grid gap-3">{recal.map(r=><div key={r.envelope_id} className="rounded-2xl bg-black/5 p-4"><strong>{r.name}</strong><p className="mt-1 text-sm">{r.reason}</p><p className="mt-2 font-black">{euro(r.current_target)} → suggestion {euro(r.suggested_target)}</p></div>)}</div>}</section>
 <section className="rounded-[28px] border border-[var(--novae-border)] bg-[var(--novae-surface)] p-5 sm:p-7"><p className="text-sm font-black">Clôture du cycle</p><p className="mt-2 text-sm text-[var(--novae-text-muted)]">{close?.message||'Calcul en cours…'}</p>{close&&close.surplus>0&&<p className="mt-3 text-2xl font-black">Surplus potentiel : {euro(close.surplus)}</p>}{close?.suggested_goal&&<p className="mt-2 text-sm">Nova peut te proposer de l’affecter à <strong>{close.suggested_goal.name}</strong>. Rien n’est déplacé sans validation.</p>}<p className="mt-2 text-sm">Espèces restantes dans les enveloppes : <strong>{euro(close?.cash_remainder)}</strong></p></section>{error&&<div className="rounded-2xl bg-red-50 p-4 text-sm text-red-800">{error}</div>}</div>}
