'use client'
import Link from 'next/link'
import { useEffect, useState } from 'react'

type Envelope={id:string;name:string;target_amount:number|string;current_amount:number|string}
type Goal={id:string;name:string;target_amount:number|string;current_amount:number|string}
type Forecast={base_balance:number|null;projected_bank_balance:number|null;real_available:number|null;cash_total:number}
type Dashboard={forecast:Forecast;envelopes:Envelope[];primary_goal:Goal|null;overdraft:{current:number;limit:number}|null}
const money=(v:number|string|null|undefined)=>v==null?'—':Number(v||0).toLocaleString('fr-FR',{maximumFractionDigits:2})

export default function FinanceDashboard(){
  const [data,setData]=useState<Dashboard|null>(null),[error,setError]=useState<string|null>(null)
  useEffect(()=>{let active=true;fetch('/api/finance/dashboard',{cache:'no-store'}).then(async r=>{const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.detail||p.error||'Impossible de charger.');if(active)setData(p)}).catch(e=>active&&setError(e instanceof Error?e.message:'Erreur'));return()=>{active=false}},[])
  const goal=data?.primary_goal??null,gt=Number(goal?.target_amount||0),gc=Number(goal?.current_amount||0),gp=gt>0?Math.min(100,Math.max(0,gc/gt*100)):0
  return <div className="grid gap-4 lg:grid-cols-[1.35fr_.65fr]">
    <section className="rounded-[28px] bg-gradient-to-br from-[var(--novae-primary)] to-[var(--novae-hero-end)] p-5 text-white shadow-lg sm:p-8"><p className="text-sm font-bold opacity-85">Disponible réellement</p><p className="mt-2 text-5xl font-black tracking-tight sm:text-6xl">{money(data?.forecast.real_available)} €</p><p className="mt-3 max-w-xl text-sm leading-6 opacity-90">Solde connu, retraits/transferts saisis, charges à venir, provisions et plancher de sécurité sont déjà intégrés.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/finances/cash" className="rounded-full bg-white px-5 py-3 text-sm font-black text-[var(--novae-primary)] no-underline">Gérer mes enveloppes physiques</Link><Link href="/finances/analysis" className="rounded-full border border-white/45 px-5 py-3 text-sm font-black text-white no-underline">Simuler une décision</Link></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-white/10 p-4"><p className="text-xs font-bold opacity-80">Solde connu</p><p className="mt-1 text-2xl font-black">{money(data?.forecast.base_balance)} €</p></div><div className="rounded-2xl bg-white/10 p-4"><p className="text-xs font-bold opacity-80">Après réserves</p><p className="mt-1 text-2xl font-black">{money(data?.forecast.projected_bank_balance)} €</p></div><div className="rounded-2xl bg-white/10 p-4"><p className="text-xs font-bold opacity-80">Cash en enveloppes</p><p className="mt-1 text-2xl font-black">{money(data?.forecast.cash_total)} €</p></div></div></section>
    {goal?<section className="rounded-[28px] border border-[var(--novae-border)] bg-[var(--novae-surface)] p-5 sm:p-6"><p className="text-sm font-black text-[var(--novae-text-muted)]">Objectif prioritaire</p><h2 className="mt-2 font-[var(--novae-font-title)] text-2xl font-semibold">{goal.name}</h2><p className="mt-3 text-sm"><strong>{money(gc)} €</strong> / {money(gt)} €</p><div className="mt-4 h-3 overflow-hidden rounded-full bg-black/10"><div className="h-full rounded-full bg-[var(--novae-primary)]" style={{width:`${gp}%`}}/></div><Link href={`/finances/goals/${goal.id}`} className="mt-4 inline-flex text-sm font-black text-[var(--novae-primary)] no-underline">Voir l’objectif →</Link></section>:<section className="rounded-[28px] border border-dashed border-[var(--novae-border)] bg-[var(--novae-surface)] p-5 sm:p-6"><p className="text-sm font-black text-[var(--novae-text-muted)]">Objectifs</p><h2 className="mt-2 text-2xl font-semibold">Aucun objectif prioritaire</h2><Link href="/finances/goals" className="mt-4 inline-flex text-sm font-black text-[var(--novae-primary)] no-underline">Ajouter un objectif →</Link></section>}
    {data?.overdraft&&<section className="rounded-[24px] border border-amber-200 bg-amber-50 p-5 text-amber-950 lg:col-span-2"><p className="text-sm font-black">Découvert configuré</p><p className="mt-1 text-sm">Découvert actuel déclaré : <strong>{money(data.overdraft.current)} €</strong>{data.overdraft.limit>0?` · autorisation ${money(data.overdraft.limit)} €`:''}.</p></section>}
    <section className="rounded-[28px] border border-[var(--novae-border)] bg-[var(--novae-surface)] p-5 sm:p-6 lg:col-span-2"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-black text-[var(--novae-text-muted)]">Mes enveloppes</p><h2 className="mt-1 text-2xl font-semibold">Budget à piloter</h2></div><Link href="/finances/envelopes" className="text-sm font-black text-[var(--novae-primary)] no-underline">Toutes les enveloppes →</Link></div>{data&&data.envelopes.length===0?<div className="mt-5 rounded-2xl border border-dashed border-[var(--novae-border)] p-6 text-center"><p className="font-bold">Aucune enveloppe configurée</p><Link href="/finances/nova" className="mt-3 inline-flex text-sm font-black text-[var(--novae-primary)] no-underline">Laisser Nova me proposer un budget →</Link></div>:<div className="mt-5 grid gap-3 md:grid-cols-3">{data?.envelopes.map(x=><Link key={x.id} href={`/finances/envelopes/${x.id}`} className="rounded-2xl border border-[var(--novae-border)] p-4 text-[var(--novae-text-main)] no-underline"><strong>{x.name}</strong><p className="mt-3 text-2xl font-black">{money(x.current_amount)} € <span className="text-sm font-semibold text-[var(--novae-text-muted)]">/ {money(x.target_amount)} €</span></p></Link>)}</div>}</section>
    <Link href="/finances/upcoming" className="rounded-[24px] border border-[var(--novae-border)] bg-[var(--novae-surface)] p-5 text-[var(--novae-text-main)] no-underline"><p className="text-sm font-black">À venir</p><p className="mt-2 text-sm text-[var(--novae-text-muted)]">Charges fixes et grosses dépenses à provisionner.</p></Link><Link href="/finances/analysis" className="rounded-[24px] border border-[var(--novae-border)] bg-[var(--novae-surface)] p-5 text-[var(--novae-text-main)] no-underline"><p className="text-sm font-black">Et si ?</p><p className="mt-2 text-sm text-[var(--novae-text-muted)]">Tester une dépense ou une épargne supplémentaire avant de décider.</p></Link>{error&&<div className="rounded-2xl bg-red-50 p-4 text-red-800 lg:col-span-2">{error}</div>}
  </div>
}
