'use client'
import Link from 'next/link'
import { useCallback, useEffect, useMemo, useState } from 'react'

type Tx={id:string;date:string;label:string;amount:number;currency:string}
type Cat={id:string;slug:string;name:string;amount:number;count:number;percentage:number;transactions:Tx[]}
type Data={summary:{total:number;categorised:number;uncategorised:number;subscriptions:number;installments:number;recurring:number;recurring_operations:number;average_confidence:number};recurring:Array<{id:string;name:string;commitment_type:string;amount:number;frequency:string;next_due_date:string|null}>;insights:Array<{id:string;title:string;summary:string}>;categories:Cat[];expense_total:number}
const palette=['#123F33','#B98A52','#7D5B4C','#6B7C6C','#B46B52','#6F6A8A','#A68A64','#7C8D9A','#9A746F','#555F54']
const money=(v:number,c='EUR')=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:c,maximumFractionDigits:2}).format(v)

export default function FinanceTransactionIntelligence(){
 const [data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(false),[message,setMessage]=useState<string|null>(null),[selected,setSelected]=useState<string|null>(null)
 const load=useCallback(async()=>{const r=await fetch('/api/finance/transactions/intelligence',{cache:'no-store'});const p=await r.json().catch(()=>({}));if(r.ok){setData(p);setSelected((old)=>old&&p.categories?.some((c:Cat)=>c.id===old)?old:(p.categories?.[0]?.id||null))}},[])
 useEffect(()=>{void load()},[load])
 async function analyse(){setLoading(true);setMessage(null);const r=await fetch('/api/finance/transactions/analyse',{method:'POST'});const p=await r.json().catch(()=>({}));if(r.ok){setMessage(`${p.analysed} opérations analysées · ${p.recurring_patterns} récurrences détectées.`);await load()}else setMessage(p.detail||p.error||'Analyse impossible.');setLoading(false)}
 const active=useMemo(()=>data?.categories.find(c=>c.id===selected)||null,[data,selected])
 const gradient=useMemo(()=>{if(!data?.categories.length)return 'conic-gradient(#e8e5df 0 100%)';let start=0;return `conic-gradient(${data.categories.map((c,i)=>{const end=start+c.percentage;const s=`${palette[i%palette.length]} ${start}% ${end}%`;start=end;return s}).join(',')})`},[data])
 return <section className="rounded-[28px] border border-[var(--novae-border)] bg-[var(--novae-surface)] p-5 sm:p-7">
  <div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[var(--novae-primary)]">Analyse des transactions</p><h2 className="mt-2 font-[var(--novae-font-title)] text-3xl font-semibold">Ce que le moteur comprend</h2></div><button onClick={()=>void analyse()} disabled={loading} className="rounded-full bg-[var(--novae-primary)] px-5 py-3 text-sm font-black text-white disabled:opacity-50">{loading?'Analyse…':'Relancer l’analyse'}</button></div>
  {data&&<><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-2xl bg-black/[.04] p-4"><small>Catégorisées</small><p className="mt-1 text-2xl font-black">{data.summary.categorised}/{data.summary.total}</p></div><div className="rounded-2xl bg-black/[.04] p-4"><small>Récurrences détectées</small><p className="mt-1 text-2xl font-black">{data.summary.recurring}</p><p className="mt-1 text-xs text-[var(--novae-text-muted)]">{data.summary.recurring_operations} opération(s) dans ces séries</p></div><div className="rounded-2xl bg-black/[.04] p-4"><small>Abonnements</small><p className="mt-1 text-2xl font-black">{data.summary.subscriptions}</p></div><div className="rounded-2xl bg-black/[.04] p-4"><small>Paiements fractionnés</small><p className="mt-1 text-2xl font-black">{data.summary.installments}</p></div></div>
  <div className="mt-6 rounded-3xl border border-[var(--novae-border)] p-4 sm:p-5"><div className="flex flex-wrap items-end justify-between gap-2"><div><h3 className="font-[var(--novae-font-title)] text-2xl font-semibold">Répartition des dépenses</h3><p className="mt-1 text-sm text-[var(--novae-text-muted)]">Clique sur une catégorie pour voir ce qu’elle contient.</p></div><strong>{money(data.expense_total)}</strong></div>
   <div className="mt-5 grid gap-6 lg:grid-cols-[240px_1fr]"><div className="mx-auto flex h-52 w-52 items-center justify-center rounded-full" style={{background:gradient}}><div className="flex h-32 w-32 flex-col items-center justify-center rounded-full bg-[var(--novae-surface)] text-center shadow-sm"><span className="text-xs text-[var(--novae-text-muted)]">Dépenses</span><strong className="mt-1 text-xl">{money(data.expense_total)}</strong></div></div>
   <div className="grid content-start gap-2">{data.categories.map((c,i)=><button key={c.id} onClick={()=>setSelected(c.id)} className={`flex items-center justify-between gap-3 rounded-2xl border p-3 text-left transition ${selected===c.id?'border-[var(--novae-primary)] bg-black/[.035]':'border-[var(--novae-border)]'}`}><span className="flex min-w-0 items-center gap-3"><span className="h-3 w-3 shrink-0 rounded-full" style={{backgroundColor:palette[i%palette.length]}}/><span className="truncate font-bold">{c.name}</span></span><span className="whitespace-nowrap text-sm"><strong>{money(c.amount)}</strong> · {c.percentage}%</span></button>)}</div></div>
   {active&&<div className="mt-6 rounded-2xl bg-black/[.03] p-4"><div className="flex flex-wrap items-end justify-between gap-2"><div><p className="text-xs font-black uppercase tracking-[.14em] text-[var(--novae-primary)]">Détail de la catégorie</p><h4 className="mt-1 text-xl font-black">{active.name}</h4></div><p className="text-sm"><strong>{money(active.amount)}</strong> · {active.count} opération(s) · {active.percentage}%</p></div><div className="mt-3 divide-y divide-[var(--novae-border)]">{active.transactions.map(tx=><Link key={tx.id} href={`/finances/transactions/${tx.id}`} className="grid grid-cols-[82px_1fr_auto] gap-2 py-3 text-sm hover:opacity-75"><span className="text-[var(--novae-text-muted)]">{new Intl.DateTimeFormat('fr-FR',{day:'2-digit',month:'short'}).format(new Date(`${tx.date}T12:00:00`))}</span><span className="truncate font-semibold">{tx.label}</span><strong className="whitespace-nowrap">{money(tx.amount,tx.currency)}</strong></Link>)}</div>{active.slug==='uncategorised'&&<p className="mt-3 text-xs text-[var(--novae-text-muted)]">Ouvre une opération pour la corriger : Nova pourra ensuite retenir la règle marchand.</p>}</div>}
  </div>
  {data.insights.length>0&&<div className="mt-5 grid gap-3 md:grid-cols-2">{data.insights.map(i=><div key={i.id} className="rounded-2xl border border-[var(--novae-border)] p-4"><strong>{i.title}</strong><p className="mt-2 text-sm text-[var(--novae-text-muted)]">{i.summary}</p></div>)}</div>}
  {data.recurring.length>0&&<div className="mt-5"><h3 className="font-black">Récurrences détectées</h3><div className="mt-3 grid gap-2">{data.recurring.map(r=><div key={r.id} className="flex flex-wrap items-center justify-between gap-2 rounded-2xl bg-black/[.035] p-4"><div><strong>{r.name}</strong><p className="text-xs text-[var(--novae-text-muted)]">{r.commitment_type==='subscription'?'Abonnement':'Dépense récurrente'} · {r.frequency==='monthly'?'mensuelle':'hebdomadaire'}</p></div><div className="text-right"><strong>{money(Number(r.amount))}</strong>{r.next_due_date&&<p className="text-xs text-[var(--novae-text-muted)]">Prochaine ≈ {new Intl.DateTimeFormat('fr-FR').format(new Date(`${r.next_due_date}T12:00:00`))}</p>}</div></div>)}</div></div>}</>}
  {message&&<div className="mt-4 rounded-2xl bg-black/[.04] p-3 text-sm">{message}</div>}
 </section>
}
