import { supabaseAdmin } from '@/lib/supabase-admin'
function nextIncomeDate(day:number|null,now=new Date()){if(!day)return null;const year=now.getFullYear(),month=now.getMonth(),endThisMonth=new Date(year,month+1,0).getDate();let date=new Date(year,month,Math.min(day,endThisMonth));if(date<=now){const endNext=new Date(year,month+2,0).getDate();date=new Date(year,month+1,Math.min(day,endNext))}return date.toISOString().slice(0,10)}
export async function buildFinanceForecast(userId:string,overrides?:{bankBalance?:number|null;extraSpend?:number;extraSavings?:number}){
 const[accounts,profile,pending,commitments,cashEnvelopes,provisions]=await Promise.all([
  supabaseAdmin.from('finance_accounts').select('balance,available_balance').eq('user_id',userId).eq('is_active',true).eq('user_enabled',true),
  supabaseAdmin.from('finance_user_profiles').select('usual_income_day,manual_bank_balance,safety_floor,usual_net_income').eq('user_id',userId).maybeSingle(),
  supabaseAdmin.from('finance_manual_bank_movements').select('bank_delta,movement_type').eq('user_id',userId).eq('status','pending'),
  supabaseAdmin.from('finance_recurring_commitments').select('name,commitment_type,amount,next_due_date,end_date,is_active').eq('user_id',userId).eq('is_active',true),
  supabaseAdmin.from('finance_envelopes').select('id,name,cash_balance').eq('user_id',userId).eq('is_active',true).eq('cash_enabled',true),
  supabaseAdmin.from('finance_future_provisions').select('id,name,target_amount,current_reserved,due_date,monthly_amount').eq('user_id',userId).eq('is_active',true),
 ]);const error=accounts.error||profile.error||pending.error||commitments.error||cashEnvelopes.error||provisions.error;if(error)throw new Error(error.message)
 const synced=(accounts.data??[]).reduce((sum,account)=>sum+Number(account.available_balance??account.balance??0),0),hasConnected=(accounts.data??[]).length>0,manual=profile.data?.manual_bank_balance==null?null:Number(profile.data.manual_bank_balance),baseBalance=overrides?.bankBalance??(hasConnected?synced:manual),incomeDate=nextIncomeDate(profile.data?.usual_income_day??null),today=new Date().toISOString().slice(0,10),upcoming=(commitments.data??[]).filter(item=>{if(item.commitment_type==='income')return false;if(!item.next_due_date)return true;return item.next_due_date>=today&&(!incomeDate||item.next_due_date<incomeDate)}),commitmentsTotal=upcoming.reduce((sum,item)=>sum+Math.abs(Number(item.amount||0)),0),pendingTotal=(pending.data??[]).reduce((sum,item)=>sum+Number(item.bank_delta||0),0),provisionReserve=(provisions.data??[]).reduce((sum,item)=>sum+Number(item.monthly_amount||0),0),extraSpend=Math.max(0,Number(overrides?.extraSpend||0)),extraSavings=Math.max(0,Number(overrides?.extraSavings||0)),safetyFloor=Math.max(0,Number(profile.data?.safety_floor||0)),projected=baseBalance==null?null:baseBalance+pendingTotal-commitmentsTotal-provisionReserve-extraSpend-extraSavings,realAvailable=projected==null?null:projected-safetyFloor,cashTotal=(cashEnvelopes.data??[]).reduce((sum,item)=>sum+Number(item.cash_balance||0),0)
 return{base_balance:baseBalance,balance_source:hasConnected?'bank':manual==null?'missing':'manual',pending_bank_delta:pendingTotal,commitments_total:commitmentsTotal,provisions_total:provisionReserve,safety_floor:safetyFloor,extra_spend:extraSpend,extra_savings:extraSavings,projected_bank_balance:projected,real_available:realAvailable,next_income_date:incomeDate,cash_total:cashTotal,cash_envelopes:cashEnvelopes.data??[],upcoming_commitments:upcoming,provisions:provisions.data??[]}
}
