import type { NextRequest } from 'next/server'
import { NextResponse } from 'next/server'
import { supabaseAdmin } from '@/lib/supabase-admin'
import { financeBadRequest, financeUnauthorized, numberOrNull, requireFinanceIdentity } from '@/lib/finance/api'

function suggestedMonthly(target:number,current:number,dueDate:string|null){ if(!dueDate) return 0; const now=new Date(); const due=new Date(`${dueDate}T12:00:00`); const months=Math.max(1,(due.getFullYear()-now.getFullYear())*12+due.getMonth()-now.getMonth()); return Math.max(0,Math.ceil((target-current)/months*100)/100) }
export async function GET(request:NextRequest){ const identity=await requireFinanceIdentity(request); if(!identity)return financeUnauthorized(); const {data,error}=await supabaseAdmin.from('finance_future_provisions').select('id,name,target_amount,current_reserved,due_date,monthly_amount,envelope_id,is_active').eq('user_id',identity.id).eq('is_active',true).order('due_date',{ascending:true}); if(error)return NextResponse.json({error:'finance_provisions_failed',detail:error.message},{status:500}); return NextResponse.json({provisions:data??[]}) }
export async function POST(request:NextRequest){ const identity=await requireFinanceIdentity(request); if(!identity)return financeUnauthorized(); const body=await request.json().catch(()=>null) as Record<string,unknown>|null; if(!body)return financeBadRequest('Données invalides.'); const name=String(body.name||'').trim(),target=numberOrNull(body.target_amount),current=numberOrNull(body.current_reserved)??0,due=body.due_date?String(body.due_date):null; if(!name||target===null||target<=0||current<0)return financeBadRequest('Provision invalide.'); const monthly=numberOrNull(body.monthly_amount)??suggestedMonthly(target,current,due); const {data,error}=await supabaseAdmin.from('finance_future_provisions').insert({user_id:identity.id,name,target_amount:target,current_reserved:current,due_date:due,monthly_amount:monthly,envelope_id:body.envelope_id?String(body.envelope_id):null,is_active:true}).select('*').single(); if(error)return NextResponse.json({error:'finance_provision_create_failed',detail:error.message},{status:500}); return NextResponse.json({provision:data},{status:201}) }
export async function DELETE(request:NextRequest){ const identity=await requireFinanceIdentity(request); if(!identity)return financeUnauthorized(); const id=new URL(request.url).searchParams.get('id'); if(!id)return financeBadRequest('Identifiant manquant.'); const {error}=await supabaseAdmin.from('finance_future_provisions').update({is_active:false,updated_at:new Date().toISOString()}).eq('id',id).eq('user_id',identity.id); if(error)return NextResponse.json({error:'finance_provision_delete_failed',detail:error.message},{status:500}); return NextResponse.json({ok:true}) }
