begin;

-- ============================================================
-- LOT 2B — anti-rejeu Nova + anti-abus public + coffre PIN
-- Aucun contenu utilisateur n'est stocke dans les tables de garde.
-- ============================================================

-- 1) Jetons d'execution Nova a usage unique
create table if not exists public.nova_execution_receipts (
  execution_id uuid primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  status text not null default 'processing' check (status in ('processing','completed','failed')),
  result_status integer,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  expires_at timestamptz not null,
  updated_at timestamptz not null default now()
);

create index if not exists idx_nova_execution_receipts_user_started
  on public.nova_execution_receipts (user_id, started_at desc);

create index if not exists idx_nova_execution_receipts_expires
  on public.nova_execution_receipts (expires_at);

alter table public.nova_execution_receipts enable row level security;

create or replace function public.begin_nova_execution(
  p_execution_id uuid,
  p_user_id uuid,
  p_expires_at timestamptz
)
returns text
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_inserted integer := 0;
  v_status text;
begin
  if p_execution_id is null or p_user_id is null or p_expires_at is null then
    raise exception 'invalid execution arguments';
  end if;

  -- Evite une croissance infinie sans ajouter de cron dedie.
  delete from public.nova_execution_receipts
  where expires_at < now() - interval '24 hours';

  insert into public.nova_execution_receipts(
    execution_id, user_id, status, expires_at
  )
  values (
    p_execution_id, p_user_id, 'processing', p_expires_at
  )
  on conflict (execution_id) do nothing;

  get diagnostics v_inserted = row_count;
  if v_inserted = 1 then
    return 'started';
  end if;

  select status
    into v_status
  from public.nova_execution_receipts
  where execution_id = p_execution_id
    and user_id = p_user_id;

  if v_status is null then
    return 'rejected';
  end if;

  return v_status;
end;
$$;

create or replace function public.finish_nova_execution(
  p_execution_id uuid,
  p_user_id uuid,
  p_status text,
  p_result_status integer default null
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if p_status not in ('completed','failed') then
    raise exception 'invalid execution status';
  end if;

  update public.nova_execution_receipts
  set
    status = p_status,
    result_status = p_result_status,
    completed_at = now(),
    updated_at = now()
  where execution_id = p_execution_id
    and user_id = p_user_id;
end;
$$;

revoke all on function public.begin_nova_execution(uuid,uuid,timestamptz) from public;
revoke all on function public.finish_nova_execution(uuid,uuid,text,integer) from public;
grant execute on function public.begin_nova_execution(uuid,uuid,timestamptz) to service_role;
grant execute on function public.finish_nova_execution(uuid,uuid,text,integer) to service_role;


-- 2) Rate limit des routes publiques sans conserver IP/email en clair.
create table if not exists public.public_request_rate_limits (
  id bigint generated by default as identity primary key,
  request_key text not null,
  action text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_public_request_limits_key_action_created
  on public.public_request_rate_limits (request_key, action, created_at desc);

alter table public.public_request_rate_limits enable row level security;

create or replace function public.consume_public_request_rate_limit(
  p_key text,
  p_action text,
  p_max integer,
  p_window_minutes integer
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_now timestamptz := now();
  v_max integer := greatest(1, least(coalesce(p_max, 10), 10000));
  v_minutes integer := greatest(1, least(coalesce(p_window_minutes, 60), 10080));
  v_count integer;
begin
  if nullif(trim(p_key), '') is null or nullif(trim(p_action), '') is null then
    raise exception 'invalid public rate-limit arguments';
  end if;

  perform pg_advisory_xact_lock(hashtext(p_key || ':' || p_action));

  select count(*)::integer
    into v_count
  from public.public_request_rate_limits
  where request_key = p_key
    and action = p_action
    and created_at >= v_now - make_interval(mins => v_minutes);

  if v_count >= v_max then
    return false;
  end if;

  insert into public.public_request_rate_limits(request_key, action, created_at)
  values (p_key, p_action, v_now);

  delete from public.public_request_rate_limits
  where created_at < v_now - interval '8 days';

  return true;
end;
$$;

revoke all on function public.consume_public_request_rate_limit(text,text,integer,integer) from public;
grant execute on function public.consume_public_request_rate_limit(text,text,integer,integer) to service_role;


-- 3) Compteur d'echecs du PIN coffre atomique
create or replace function public.record_vault_pin_failure(
  p_user_id uuid,
  p_max_attempts integer default 5,
  p_lock_minutes integer default 10
)
returns table(
  failed_attempts integer,
  locked_until timestamptz
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_attempts integer;
  v_locked_until timestamptz;
  v_max integer := greatest(1, least(coalesce(p_max_attempts, 5), 20));
  v_lock_minutes integer := greatest(1, least(coalesce(p_lock_minutes, 10), 1440));
begin
  perform pg_advisory_xact_lock(hashtext('vault:' || p_user_id::text));

  update public.user_security_settings
  set
    vault_failed_attempts = case
      when vault_locked_until is not null and vault_locked_until <= now() then 1
      else coalesce(vault_failed_attempts, 0) + 1
    end,
    vault_locked_until = case
      when (
        case
          when vault_locked_until is not null and vault_locked_until <= now() then 1
          else coalesce(vault_failed_attempts, 0) + 1
        end
      ) >= v_max
      then now() + make_interval(mins => v_lock_minutes)
      else null
    end,
    updated_at = now()
  where user_id = p_user_id
  returning vault_failed_attempts, vault_locked_until
  into v_attempts, v_locked_until;

  if not found then
    raise exception 'vault settings not found';
  end if;

  return query select v_attempts, v_locked_until;
end;
$$;

revoke all on function public.record_vault_pin_failure(uuid,integer,integer) from public;
grant execute on function public.record_vault_pin_failure(uuid,integer,integer) to service_role;

commit;
